language: php

matrix:
  include:
    - php: 7.1
      env: TO_TEST=PHPUNIT
    - php: 7.1
      env: TO_TEST=CODECEPTION
  fast_finish: true

before_script:
  - composer self-update
  - composer global require hirak/prestissimo
  - composer install --prefer-source --no-interaction --dev
  - mkdir -p build/logs

script:
 - if [ "$TO_TEST" = "PHPUNIT" ]; then php vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml tests/Unit; fi
 - if [ "$TO_TEST" = "CODECEPTION" ]; then cd tests/Integrational && php ../../vendor/bin/codecept run Unit; fi
