language: php

matrix:
  include:
    - php: 7.1
      env: TO_TEST=PHPUNIT
    - php: 7.1
      env: TO_TEST=CODECEPTION
    - php: 7.2
      env: TO_TEST=PHPUNIT
    - php: 7.2
      env: TO_TEST=CODECEPTION
  fast_finish: true

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mkdir -p build/logs

script:
 - if [ "$TO_TEST" = "PHPUNIT" ]; then php vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml tests/Unit; fi
 - if [ "$TO_TEST" = "CODECEPTION" ]; then cd tests/Integrational && php ../../vendor/bin/codecept run Unit; fi
